name: Prerelease

on:
  pull_request:
    types: [closed]
    paths:
      - 'packages/**'
    branches: [main]

jobs:
  # Creates or Updates release PR
  release_pr:
    name: Create/Update Release PR
    if: ${{ !startsWith(github.head_ref, 'release-') }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    outputs:
      prs: ${{ steps.release.outputs.prs }}

    steps:
      - uses: actions/checkout@v3

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.BOT_TOKEN }}
          config-file: release-please-prerelease.json

      - name: get release branch
        run: |
          echo "prs = ${{ steps.release.outputs.prs }}"

  publish_prerelease:
    name: Trigger prerelease package publish
    if: ${{ needs.release_pr.outputs.prs != '' }}
    runs-on: [self-hosted, dj-ubuntu-2004-latest, ARM64]
    needs: release_pr
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.release_pr.outputs.prs) }}
    steps:
      - name: Get package name
        run: echo "PACKAGE_NAME=${{ matrix.package.title }}" | cut -d' ' -f3 >> $GITHUB_ENV
