name: Prerelease

on:
  pull_request:
    types: [closed]
    paths:
      - 'packages/**'
    branches: [main]

jobs:
  # Creates or Updates release PR
  release_pr:
    name: Create/Update Release PR
    if: ${{ !startsWith(github.head_ref, 'release-') }}
    runs-on: ubuntu-latest
    timeout-minutes: 30

    outputs:
      prs: ${{ steps.release.outputs.prs }}

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.BOT_TOKEN }}
          config-file: release-please-config.json
          skip-github-release: true

  publish_prerelease:
    name: Trigger prerelease package publish
    if: ${{ needs.release_pr.outputs.prs != '' }}
    runs-on: ubuntu-latest
    needs: release_pr
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.release_pr.outputs.prs) }}
    steps:
      - name: Get package name
        run: |
          PACKAGE_NAME= $(echo ${{ matrix.package.title }} | cut -d' ' -f3)
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
